name: SSH Deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - run: npm i
      #- run: npm run build

      - name: Synchromize files to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ secrets.WORK_DIR }}

      - name: Run remote script
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            npm install
            pm2 restart 8

      # - name: Deploy to VPS
      #   uses: nogsantos/scp-deploy@master
      #   with:
      #     src: /home/runner/work/github-action-node1/github-action-node1
      #     host: ${{ secrets.SSH_HOST }}
      #     remote: ${{ secrets.WORK_DIR }}
      #     port: ${{ secrets.SSH_PORT }}
      #     user: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
